import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, folder1, folder2 }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ padding: '50px' }}>
        <h1>Parallel routes</h1>
        <div style={{ padding: '20px' }}>
          {folder1}
        </div>
        <div style={{ padding: '20px' }}>
          {folder2}
        </div>
        {children}
      </body>
    </html>
  )
}